# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-17 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginReg', '0004_auto_20180417_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password1',
            field=models.CharField(default='', max_length=15),
        ),
    ]
