# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-17 13:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginReg', '0005_userprofile_password1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password1',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
